/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendadevehiculos;

import Modelo.Bitacora;
import Modelo.ControladorVehiculo;
import Modelo.Vehiculo;
import Modelo.controladorBitacora;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author johan
 */
public class FrmBitacoraSalidas extends javax.swing.JInternalFrame {
     public static Bitacora bitacoraActual;
      controladorBitacora controladorBitacora=new controladorBitacora();
      ControladorVehiculo controladorVehiculo=new ControladorVehiculo();
    
    
    /**
     * Creates new form FrmBitacora
     */
    public FrmBitacoraSalidas() {
      
        initComponents();
        Date d =new Date(); 
        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yyyy");
        txtFechaSalida.setText(f.format(d));
        txtHoraSalida.setText(d.getHours()+ ":" +d.getMinutes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPlaca = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        cbProvincia = new javax.swing.JComboBox<>();
        txtDestino = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();
        txtHoraSalida = new javax.swing.JTextField();
        SpnKilometrajeInicial = new javax.swing.JSpinner();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de salidas"));

        txtPlaca.setBorder(javax.swing.BorderFactory.createTitledBorder("Placa"));
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));

        cbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Jose", "Puntarenas", "Heridia", "Cartago", "Limon", "Alajuela", "Guanacaste" }));
        cbProvincia.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincia"));

        txtDestino.setBorder(javax.swing.BorderFactory.createTitledBorder("Destino"));

        txtFechaSalida.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de salida"));

        txtHoraSalida.setBorder(javax.swing.BorderFactory.createTitledBorder("Hora de salida"));

        SpnKilometrajeInicial.setBorder(javax.swing.BorderFactory.createTitledBorder("Kilometraje inicial"));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbProvincia, javax.swing.GroupLayout.Alignment.LEADING, 0, 154, Short.MAX_VALUE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtDescripcion)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(SpnKilometrajeInicial)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(txtFechaSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(SpnKilometrajeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      
         
         controladorBitacora.conectar();
         controladorVehiculo.conectar();
         if (!txtPlaca.getText().isEmpty() && !txtDestino.getText().isEmpty()
                && !txtFechaSalida.getText().isEmpty() && !txtHoraSalida.getText().isEmpty()) {
            
            if (controladorVehiculo.validarPK(new Vehiculo(txtPlaca.getText()))) {
                Bitacora bitacora = new Bitacora();
                bitacora.setPlaca(controladorVehiculo.buscar(new Vehiculo(txtPlaca.getText())));
                System.out.println(bitacora);
                if (controladorBitacora.validarPK(bitacora) 
                        || !controladorBitacora.validarPK(bitacora)
                        && controladorBitacora.buscar(bitacora).getFechaLlegada() != null) {

                    
                    System.out.println(controladorBitacora.buscar(bitacora));
                    bitacora.setDestino(txtDestino.getText());
                    bitacora.setProvincia(cbProvincia.getItemAt(cbProvincia.getSelectedIndex()));
                    bitacora.setKInical((int) SpnKilometrajeInicial.getValue());
                    System.out.println(bitacora);
                    if (controladorBitacora.Agregar(bitacora)) {
                        bitacoraActual = bitacora;
                        JOptionPane.showMessageDialog(this, "Informacion Guardada");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al Guardar");
               } } } 
        } else {
            JOptionPane.showMessageDialog(this, "Falta información.");
        }    
    }//GEN-LAST:event_btnGuardarActionPerformed

   
    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
          String descripcion = txtPlaca.getText();
        if (descripcion != null) {
            Vehiculo carro = new Vehiculo(descripcion);
            Bitacora bita = new Bitacora(carro);
            Vehiculo mod = controladorVehiculo.buscar(carro);

            if (!controladorBitacora.validarPK(bita)) {
                txtDescripcion.setText(mod.getDescripcion());
                
                Bitacora bitamod = controladorBitacora.buscar(bita);
                SpinnerNumberModel nm = new SpinnerNumberModel();
                nm.setMinimum(bitamod.getKFinal());
                SpnKilometrajeInicial.setModel(nm);
                SpnKilometrajeInicial.setValue(bitamod.getKFinal());
            } else {
                JOptionPane.showMessageDialog(null, "Placa no existe", "Error", 0);
            }
        }
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnKilometrajeInicial;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbProvincia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    
}
